# Generated by Django 4.1.4 on 2022-12-26 19:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Movies',
            fields=[
                ('movietitle', models.CharField(db_column='movieTitle', max_length=50, primary_key=True, serialize=False)),
                ('releasedate', models.DateField(blank=True, db_column='releaseDate', null=True)),
                ('genre', models.CharField(blank=True, max_length=20, null=True)),
                ('rating', models.CharField(blank=True, max_length=20, null=True)),
                ('gross', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'Movies',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Actorsinmovies',
            fields=[
                ('movie', models.OneToOneField(db_column='movie', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='Disney_App.movies')),
                ('actor', models.CharField(max_length=50)),
                ('actorrole', models.CharField(db_column='actorRole', max_length=50)),
            ],
            options={
                'db_table': 'ActorsInMovies',
                'managed': False,
            },
        ),
    ]
